# size of the kit gui (must be rows * 9)
kit_gui_size: 27
# size of the shop gui (must be rows * 9)
shop_gui_size: 27
# combat timer (seconds)
combat_timer: 15
# commands that are blocked if a player is in combat
blocked_commands:
  - "/spawn"
  - "/kit"
  - "/shop"
# mongodb
connection_uri: replace
database: replace
kit_collection: replace
shop_collection: replace
user_collection: replace