name: PVPCore
version: '${project.version}'
main: me.crackma.pvpcore.PVPCorePlugin
api-version: '1.20'
author: crackma
website: https://github.com/crackma/
softdepend: [PlaceholderAPI]
commands:
  createkit:
    description: Create kits.
    usage: §c/createkit <kit_name> <cooldown> <inventoryPosition> <display_item>
    permission: pvpcore.managekits
    permission-message: §cYou cannot do that.
  deletekit:
    description: Delete kits.
    usage: §c/deletekit <kit_name>
    permission: pvpcore.managekits
    permission-message: §cYou cannot do that.
  kit:
    description: Claim kits.
    aliases: kits
    usage: §c/<command> <kit_name> [player]
  leaderboard:
    description: View the top players.
    aliases: [lb, top]
  category:
    description: Edit the categories of the shop
    usage: §c/category help
    permission: pvpcore.editcategories
    permission-message: §cYou cannot do that.
  shop:
    description: Buy items.
    usage: §c/shop
  exitcombat:
    description: Sets the combat timer to 0.
    permission: pvpcore.exitcombat
    permission-message: §cYou cannot do that.
  stats:
    description: View players' stats.
    usage: §c/stats [player]
  editstats:
    description: Edit players' stats.
    usage: §c/editstats <player> <kills> <deaths> <streak> <gems>
    permission: pvpcore.editstats
    permission-message: §cYou cannot do that.