name: PVPCore
version: '${project.version}'
main: me.crackma.pvpcore.PVPCorePlugin
api-version: 1.19
author: crackma
softdepend: [PlaceholderAPI]
commands:
  createkit:
    description: Create kits.
    usage: §c/createkit <kit_name> <cooldown> <inventoryPosition> <display_item>
    permission: pvpcore.managekits
    permission-message: §cYou cannot do that.
  deletekit:
    description: Delete kits.
    usage: §c/deletekit <kit_name>
    permission: pvpcore.managekits
    permission-message: §cYou cannot do that.
  kit:
    description: Claim kits.
    usage: §c/kit <kit_name> [player]
  category:
    description: Edit the categories of the shop
    usage: §c/category help
    permission: pvpcore.editcategories
    permission-message: §cYou cannot do that.
  shop:
    description: Buy items.
    usage: §c/shop
  stats:
    description: View players' stats.
    usage: §c/stats [player]
  editstats:
    description: Edit players' stats.
    usage: §c/editstats <player> <kills> <deaths> <streak> <gems>
    permission: pvpcore.editstats
    permission-message: §cYou cannot do that.